dataset_path: D:\Code\Datasets\ImageNet100\imagenet-100
ckpt_path: ~
device: cuda
num_class: 100
batch_size: 64
epochs: 40
usetqdm: true
need_valid: false
warm: 
  warmup: true
  warmup_epochs: 10
  warmup_multiple: 10
optimize_level: O0
optimizer_type: SGD
optimizer_save_path: ~
lr: 0.01
lr_decay: CosineAnnealingLR
weight_decay: 0.01
valid_per_epoch: 1
valid_in_epoch: ~
save_per_epoch: 1
save_in_epoch: ~