dataset_path: D:\Code\Datasets\ImageNet100\imagenet-100
ckpt_path: D:/Code/CVModel/pretrained_weights/resnet50-0676ba61.pth
device: cuda
num_class: 100
batch_size: 16
epochs: 40
warm: 
  warmup: true
  warmup_epochs: 1
  warmup_multiple: 1000
optimize_level: O1
optimizer_type: Adam
lr: 0.01
lr_decay: CosineAnnealingLR
weight_decay: 0.01
valid_per_epoch: 1
valid_in_epoch: ~
save_per_epoch: 1
save_in_epoch: ~